services:
  - type: web
    name: cafe-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cafe-manager-backend.onrender.com
